Algoritmo " ESCADAS"

Var
   alturafinal:real
   degrau: real
   altura: real
   


Inicio
           escreva (" digite a altura que deseja alcançar ")
           leia ( altura)
           escreva (" digite a altura de cada degrau ")
           leia ( degrau)
           
                alturafinal<- altura / degrau
                
                escreva ( "você deve subir ", alturafinal)


Fimalgoritmo